In [1]:
import torch

## 1. Indexing
### 1.1. Sử sử dụng `index` và `slice`

In [2]:
# chỉ mục với tensor 1D

t1 = torch.arange(0, 30, 3)
t1

tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27])

In [3]:
t1[0], t1[4], t1[9] # kết quả khi lấy chỉ mục vẫn là một tensor

(tensor(0), tensor(12), tensor(27))

In [4]:
# slice
t1[2:6]

tensor([ 6,  9, 12, 15])

In [5]:
t1[1:7:2] # thêm step

tensor([ 3,  9, 15])

In [6]:
t1[1::2], t1[:8:2]

(tensor([ 3,  9, 15, 21, 27]), tensor([ 0,  6, 12, 18]))

In [7]:
# chỉ mục với tensor 2D
t2 = torch.arange(1, 25).reshape((4, 6))
t2

tensor([[ 1,  2,  3,  4,  5,  6],
        [ 7,  8,  9, 10, 11, 12],
        [13, 14, 15, 16, 17, 18],
        [19, 20, 21, 22, 23, 24]])

In [8]:
t2[1, 2], t2[:2, 2], t2[1, ::2], t2[1, [0,2,4]], t2[[3, 2], 4], t2[::2, ::4]

(tensor(9),
 tensor([3, 9]),
 tensor([ 7,  9, 11]),
 tensor([ 7,  9, 11]),
 tensor([23, 17]),
 tensor([[ 1,  5],
         [13, 17]]))

In [9]:
# chỉ mục với tensor 3D

t3 = torch.arange(1, 121).reshape((4, 5, 6))
t3

tensor([[[  1,   2,   3,   4,   5,   6],
         [  7,   8,   9,  10,  11,  12],
         [ 13,  14,  15,  16,  17,  18],
         [ 19,  20,  21,  22,  23,  24],
         [ 25,  26,  27,  28,  29,  30]],

        [[ 31,  32,  33,  34,  35,  36],
         [ 37,  38,  39,  40,  41,  42],
         [ 43,  44,  45,  46,  47,  48],
         [ 49,  50,  51,  52,  53,  54],
         [ 55,  56,  57,  58,  59,  60]],

        [[ 61,  62,  63,  64,  65,  66],
         [ 67,  68,  69,  70,  71,  72],
         [ 73,  74,  75,  76,  77,  78],
         [ 79,  80,  81,  82,  83,  84],
         [ 85,  86,  87,  88,  89,  90]],

        [[ 91,  92,  93,  94,  95,  96],
         [ 97,  98,  99, 100, 101, 102],
         [103, 104, 105, 106, 107, 108],
         [109, 110, 111, 112, 113, 114],
         [115, 116, 117, 118, 119, 120]]])

In [10]:
t3[1, 3, 5], t3[2, ::2, ::2], t3[2:, ::2, ::2]

(tensor(54),
 tensor([[61, 63, 65],
         [73, 75, 77],
         [85, 87, 89]]),
 tensor([[[ 61,  63,  65],
          [ 73,  75,  77],
          [ 85,  87,  89]],
 
         [[ 91,  93,  95],
          [103, 105, 107],
          [115, 117, 119]]]))

### 1.2. Sử dụng hàm trong torch

In [11]:
t1.ndim, t1

(1, tensor([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27]))

In [12]:
# sủ dụng: index_select để lập chỉ mục
indices = torch.tensor([1, 3])
torch.index_select(t1, 0, indices)

tensor([3, 9])

In [13]:
t2.shape, t2

(torch.Size([4, 6]),
 tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]]))

In [14]:
torch.index_select(t2, 0, indices), torch.index_select(t2, 1, indices)

(tensor([[ 7,  8,  9, 10, 11, 12],
         [19, 20, 21, 22, 23, 24]]),
 tensor([[ 2,  4],
         [ 8, 10],
         [14, 16],
         [20, 22]]))

## 2. `torch.view()`
Phương thức `torch.view()` trong PyTorch được sử dụng để thay đổi kích thước (shape) của tensor mà không thay đổi dữ liệu của tensor đó. Phương thức này trả về một tensor mới, có cùng dữ liệu với tensor ban đầu, nhưng với kích thước khác.

Tuy nhiên, đây cũng tương đương như shallow copy nên khi thay đổi một tensor thì tensor khác cũng được thay đổi.


In [15]:
t2_view = t2.view(3, 8)
t2, t2.shape, t2_view, t2_view.shape

(tensor([[ 1,  2,  3,  4,  5,  6],
         [ 7,  8,  9, 10, 11, 12],
         [13, 14, 15, 16, 17, 18],
         [19, 20, 21, 22, 23, 24]]),
 torch.Size([4, 6]),
 tensor([[ 1,  2,  3,  4,  5,  6,  7,  8],
         [ 9, 10, 11, 12, 13, 14, 15, 16],
         [17, 18, 19, 20, 21, 22, 23, 24]]),
 torch.Size([3, 8]))

In [16]:
t2[1, ::2] = 1000
t2, t2_view

(tensor([[   1,    2,    3,    4,    5,    6],
         [1000,    8, 1000,   10, 1000,   12],
         [  13,   14,   15,   16,   17,   18],
         [  19,   20,   21,   22,   23,   24]]),
 tensor([[   1,    2,    3,    4,    5,    6, 1000,    8],
         [1000,   10, 1000,   12,   13,   14,   15,   16],
         [  17,   18,   19,   20,   21,   22,   23,   24]]))

In [17]:
t2_view[1, ::2] = 500
t2, t2_view

(tensor([[   1,    2,    3,    4,    5,    6],
         [1000,    8,  500,   10,  500,   12],
         [ 500,   14,  500,   16,   17,   18],
         [  19,   20,   21,   22,   23,   24]]),
 tensor([[   1,    2,    3,    4,    5,    6, 1000,    8],
         [ 500,   10,  500,   12,  500,   14,  500,   16],
         [  17,   18,   19,   20,   21,   22,   23,   24]]))

In [18]:
t2_view_3d = t2.view(2,3, 4)
t2, t2_view_3d

(tensor([[   1,    2,    3,    4,    5,    6],
         [1000,    8,  500,   10,  500,   12],
         [ 500,   14,  500,   16,   17,   18],
         [  19,   20,   21,   22,   23,   24]]),
 tensor([[[   1,    2,    3,    4],
          [   5,    6, 1000,    8],
          [ 500,   10,  500,   12]],
 
         [[ 500,   14,  500,   16],
          [  17,   18,   19,   20],
          [  21,   22,   23,   24]]]))

In [19]:
t2[2:, :1] = 2222
t2, t2_view_3d

(tensor([[   1,    2,    3,    4,    5,    6],
         [1000,    8,  500,   10,  500,   12],
         [2222,   14,  500,   16,   17,   18],
         [2222,   20,   21,   22,   23,   24]]),
 tensor([[[   1,    2,    3,    4],
          [   5,    6, 1000,    8],
          [ 500,   10,  500,   12]],
 
         [[2222,   14,  500,   16],
          [  17,   18, 2222,   20],
          [  21,   22,   23,   24]]]))

## 3. Slicing
- Phương thức `torch.chunk()` trong PyTorch được sử dụng để chia một tensor thành các tensor con theo một chiều được chỉ định. Cú pháp sử dụng của phương thức này như sau:

`torch.chunk(input, chunks, dim=0)`

Trong đó:

    - input: là tensor cần được chia nhỏ.
    - chunks: là số lượng các tensor con cần tạo.
    - dim: là chiều của tensor mà ta muốn thực hiện phép chia. Mặc định là 0.

In [20]:
t2_chunked = torch.chunk(t2, 4, dim=0)
t2, t2_chunked, t2_chunked[1][0]

(tensor([[   1,    2,    3,    4,    5,    6],
         [1000,    8,  500,   10,  500,   12],
         [2222,   14,  500,   16,   17,   18],
         [2222,   20,   21,   22,   23,   24]]),
 (tensor([[1, 2, 3, 4, 5, 6]]),
  tensor([[1000,    8,  500,   10,  500,   12]]),
  tensor([[2222,   14,  500,   16,   17,   18]]),
  tensor([[2222,   20,   21,   22,   23,   24]])),
 tensor([1000,    8,  500,   10,  500,   12]))

In [21]:
t2_chunked[1][0][::2] = 100
t2, t2_chunked, t2_chunked[1][0]

(tensor([[   1,    2,    3,    4,    5,    6],
         [ 100,    8,  100,   10,  100,   12],
         [2222,   14,  500,   16,   17,   18],
         [2222,   20,   21,   22,   23,   24]]),
 (tensor([[1, 2, 3, 4, 5, 6]]),
  tensor([[100,   8, 100,  10, 100,  12]]),
  tensor([[2222,   14,  500,   16,   17,   18]]),
  tensor([[2222,   20,   21,   22,   23,   24]])),
 tensor([100,   8, 100,  10, 100,  12]))

In [22]:
# khi số lượng phần tử ở tensor ban đầu không chia hết cho số chunk chỉ định thì sẽ không báo lỗi mà 
# nó sẽ được chia theo cách khác hợp lý  hơn

torch.chunk(t2, 3, dim=0), torch.chunk(t2, 7, dim=1)

((tensor([[  1,   2,   3,   4,   5,   6],
          [100,   8, 100,  10, 100,  12]]),
  tensor([[2222,   14,  500,   16,   17,   18],
          [2222,   20,   21,   22,   23,   24]])),
 (tensor([[   1],
          [ 100],
          [2222],
          [2222]]),
  tensor([[ 2],
          [ 8],
          [14],
          [20]]),
  tensor([[  3],
          [100],
          [500],
          [ 21]]),
  tensor([[ 4],
          [10],
          [16],
          [22]]),
  tensor([[  5],
          [100],
          [ 17],
          [ 23]]),
  tensor([[ 6],
          [12],
          [18],
          [24]])))

Phương thức `torch.split('tensor', 'num_of_tensor', 'dim')` trong PyTorch được sử dụng để chia một tensor thành các tensor con theo một chiều cụ thể.

In [30]:
t2_splitted = torch.split(t2, 2, 0)
t2_splitted

(tensor([[  1,   2,   3,   4,   5,   6],
         [100,   8, 100,  10, 100,  12]]),
 tensor([[2222,   14,  500,   16,   17,   18],
         [2222,   20,   21,   22,   23,   24]]))

In [39]:
torch.split(t2, [3, 1], 0), torch.split(t2, [1, 2, 1], 0)

# torch.split(t2, [1, 2, 3], 0) -> RuntimeError  vì tổng số tensor con cần chi vượt kích thước chiều được chia theo

((tensor([[   1,    2,    3,    4,    5,    6],
          [ 100,    8,  100,   10,  100,   12],
          [2222,   14,  500,   16,   17,   18]]),
  tensor([[2222,   20,   21,   22,   23,   24]])),
 (tensor([[1, 2, 3, 4, 5, 6]]),
  tensor([[ 100,    8,  100,   10,  100,   12],
          [2222,   14,  500,   16,   17,   18]]),
  tensor([[2222,   20,   21,   22,   23,   24]])))

In [41]:
torch.split(t2, [1, 2, 1, 2], 1)

(tensor([[   1],
         [ 100],
         [2222],
         [2222]]),
 tensor([[  2,   3],
         [  8, 100],
         [ 14, 500],
         [ 20,  21]]),
 tensor([[ 4],
         [10],
         [16],
         [22]]),
 tensor([[  5,   6],
         [100,  12],
         [ 17,  18],
         [ 23,  24]]))

In [43]:
t2_splitted[1][:1, ::2] = -10000 # chỉnh sửa thay đổi cả 2 tensor
t2, t2_splitted

(tensor([[     1,      2,      3,      4,      5,      6],
         [   100,      8,    100,     10,    100,     12],
         [-10000,     14, -10000,     16, -10000,     18],
         [  2222,     20,     21,     22,     23,     24]]),
 (tensor([[  1,   2,   3,   4,   5,   6],
          [100,   8, 100,  10, 100,  12]]),
  tensor([[-10000,     14, -10000,     16, -10000,     18],
          [  2222,     20,     21,     22,     23,     24]])))

## 4. Merger
Kết hợp các tensor thành một tensor lớn hơn bằng cách nối hoặc xếp các tensor với nhau tương tự như việc thêm phần tử vào list

- `torch.cat()` dùng để nối các tensor cùng kích thước trên một chiều nhất định. Nó cũng có thể được sử dụng để nối các tensor có số chiều khác nhau, tuy nhiên, ta cần chỉ định trục nào được sử dụng để nối.

- `torch.stack()` dùng để xếp các tensor lên nhau để tạo ra một tensor mới có số chiều lớn hơn.


In [44]:
# sử dụng cat()

a = torch.zeros(2, 3)
b = torch.ones(2, 3)
c = torch.zeros(3, 3)
a, b, c

(tensor([[0., 0., 0.],
         [0., 0., 0.]]),
 tensor([[1., 1., 1.],
         [1., 1., 1.]]),
 tensor([[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]]))

In [47]:
# nối theo hàng, dim: mặc định là 0

torch.cat([a, b])

tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])

In [49]:
# torch.cat([a, c], dim=1)  -> RuntimeError: vì kích thước 2 tensor không tương thích

torch.cat([a,b], dim=1)

tensor([[0., 0., 0., 1., 1., 1.],
        [0., 0., 0., 1., 1., 1.]])

In [50]:
# sử dụng stack
a.shape, b.shape, c.shape

(torch.Size([2, 3]), torch.Size([2, 3]), torch.Size([3, 3]))

In [53]:
# torch.stack([a, c]) -> RuntimeError: kích thước các tensor xếp phải giống nhau
torch.stack([a, b]), torch.stack([a, b]).shape

(tensor([[[0., 0., 0.],
          [0., 0., 0.]],
 
         [[1., 1., 1.],
          [1., 1., 1.]]]),
 torch.Size([2, 2, 3]))

#### Khác biệt của hai phương thức:

- Khi sử dụng phương thức `torch.cat()`, sau khi nối (concatenate) các tensor lại với nhau, số chiều của tensor kết quả vẫn giữ nguyên. Trong khi đó, sử dụng phương thức `torch.stack()`, số chiều của tensor kết quả sẽ tăng lên một đơn vị.

- Khi sử dụng `torch.cat()`, các tensor được nối vào cùng một tensor kết quả. Trong khi đó, với `torch.stack()`, các tensor được xếp chồng lên nhau và được bọc trong một tensor kết quả mới.

- Vì các tensor được xếp chồng lên nhau trong phương thức`torch.stack()`, nó yêu cầu các tensor được xếp chồng phải có cùng kích thước tại tất cả các chiều. Trong khi đó, `torch.cat()` có thể nối các tensor có kích thước khác nhau tại một số chiều được chỉ định.

### 5. Tensor dimensional adjustment

- Bằng phương thức `reshape`, ta có thể linh hoạt điều chỉnh hình dạng của Tensor. Trong quá trình tính toán với Tensor, thường cần thực hiện thêm các thao tác giảm hoặc tăng số chiều của Tensor:

- Khi cần loại bỏ các chiều không cần thiết, ta có thể sử dụng hàm `squeeze`
- Khi cần tăng số chiều một cách thủ công, ta có thể sử dụng hàm `unsqueeze`

In [65]:
t4 = torch.ones(3, 2, 3, 2) # 
t4, t4.ndim, t4.shape, t4.reshape((4, 3 , 3))

(tensor([[[[1., 1.],
           [1., 1.],
           [1., 1.]],
 
          [[1., 1.],
           [1., 1.],
           [1., 1.]]],
 
 
         [[[1., 1.],
           [1., 1.],
           [1., 1.]],
 
          [[1., 1.],
           [1., 1.],
           [1., 1.]]],
 
 
         [[[1., 1.],
           [1., 1.],
           [1., 1.]],
 
          [[1., 1.],
           [1., 1.],
           [1., 1.]]]]),
 4,
 torch.Size([3, 2, 3, 2]),
 tensor([[[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]],
 
         [[1., 1., 1.],
          [1., 1., 1.],
          [1., 1., 1.]]]))

In [67]:
t5 = torch.ones(1, 1, 3, 1)
t5.ndim, t5.shape, t5

(4,
 torch.Size([1, 1, 3, 1]),
 tensor([[[[1.],
           [1.],
           [1.]]]]))

In [70]:
# squeeze

t5_squeezed = torch.squeeze(t5)
t5, t5_squeezed, t5_squeezed.shape

(tensor([[[[1.],
           [1.],
           [1.]]]]),
 tensor([1., 1., 1.]),
 torch.Size([3]))

In [72]:
t6 = torch.ones(1,1,3,2,1,2)
t6, t6.ndim, t6.shape

(tensor([[[[[[1., 1.]],
 
            [[1., 1.]]],
 
 
           [[[1., 1.]],
 
            [[1., 1.]]],
 
 
           [[[1., 1.]],
 
            [[1., 1.]]]]]]),
 6,
 torch.Size([1, 1, 3, 2, 1, 2]))

In [73]:
torch.squeeze(t6), torch.squeeze(t6).ndim, torch.squeeze(t6).shape

(tensor([[[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]],
 
         [[1., 1.],
          [1., 1.]]]),
 3,
 torch.Size([3, 2, 2]))

In [78]:
# unsqueeze

t7 = torch.full((1, 2, 1, 3), 5)
t7, t7.shape



(tensor([[[[5, 5, 5]],
 
          [[5, 5, 5]]]]),
 torch.Size([1, 2, 1, 3]))

In [81]:
t7_unsqueezed = torch.unsqueeze(t7, dim=0)
t7_unsqueezed, t7_unsqueezed.shape

(tensor([[[[[5, 5, 5]],
 
           [[5, 5, 5]]]]]),
 torch.Size([1, 1, 2, 1, 3]))

In [83]:
torch.unsqueeze(t7, dim=2).shape, torch.unsqueeze(t7, dim=4).shape

(torch.Size([1, 2, 1, 1, 3]), torch.Size([1, 2, 1, 3, 1]))