Là loại dữ liệu cơ bản để thực hiện các thuật toán học sâu trong PyTorch, Tensor cũng có rất nhiều hàm toán học và phương pháp tính toán tương ứng với một loạt các quy tắc tính toán. Trong PyTorch, các phép tính được áp dụng trên Tensor được gọi chung là toán tử (operations). So với NumPy, PyTorch cung cấp phân loại toán tử (phép tính) cụ thể hơn, giúp người dùng dễ dàng lựa chọn toán tử (phép tính) phù hợp với các tình huống khác nhau.

PyTorch đã thiết kế sáu loại phép tính toán học cho Tensor, bao gồm:

- `Phép tính điểm (Pointwise Ops)`: thực hiện các phép tính giống nhau trên từng phần tử trong Tensor.
- `Phép tính rút gọn (Reduction Ops)`: thực hiện các phép tính trên một Tensor để thu được một giá trị tóm tắt.
- `Phép so sánh (Comparison Ops)`: thực hiện các phép so sánh giữa nhiều Tensor.
- `Phép tính phổ (Spectral Ops)`: thực hiện các phép tính liên quan đến biến đổi Fourier trong xử lý tín hiệu.
- `Phép tính BLAS và LAPACK`: thực hiện các hàm và phương pháp chính được định nghĩa trong bộ phần mềm Basic Linear Algeria Subprograms và Linear Algeria Package, được sử dụng chủ yếu trong tính toán khoa học tuyến tính.
- `Các phép tính khác (Other Ops)`: các phép tính toán học không được phân loại vào các loại trên.

## 1. Tensor broadcasting
Tensor broadcasting là một tính năng trong PyTorch (và NumPy) cho phép các phép toán được thực hiện trên các tensor có kích thước khác nhau. Nó cho phép PyTorch tự động mở rộng các tensor với số chiều thấp hơn cho phù hợp với số chiều cao hơn và thực hiện phép toán giữa chúng. Trong quá trình broadcasting, các phép toán được thực hiện trên các tensor có kích thước khác nhau nhưng các phép toán đó được thực hiện theo các quy tắc được xác định trước để đảm bảo tính chính xác và hiệu quả của phép toán.

In [1]:
import torch

### 1.1. Tính toán trên các tensor cùng hình dạng

In [2]:
# tính toán trên các tensor cùng hình dạng

t1 = torch.arange(3)
t1

tensor([0, 1, 2])

In [3]:
t1 + t1

tensor([0, 2, 4])

In [4]:
# tensor với một số

t1 + 3, t1 + torch.tensor(3)

(tensor([3, 4, 5]), tensor([3, 4, 5]))

In [5]:
# vector 2D với một số
t2 = torch.randn(3, 4)
t2, t2 + 3

(tensor([[-0.8862,  0.5172,  0.9409,  0.0777],
         [-1.2430, -0.2594, -1.6787,  2.0074],
         [-0.2995,  0.6411,  0.6727, -1.9627]]),
 tensor([[2.1138, 3.5172, 3.9409, 3.0777],
         [1.7570, 2.7406, 1.3213, 5.0074],
         [2.7005, 3.6411, 3.6727, 1.0373]]))

In [6]:
t3 = torch.ones(1, 4)
t3.shape, t2.shape # cùng kích thước

(torch.Size([1, 4]), torch.Size([3, 4]))

### 1.2. Tensor khác hình dạng
Broadcasting là quá trình trong đó khi tính toán trên các tensor có hình dạng khác nhau, một hoặc nhiều tensor được chuyển đổi ngầm thành hai tensor có cùng hình dạng, từ đó hoàn thành phép tính.

In [7]:
# tensor khác hình dạng

t2, t3, t2 + t3

(tensor([[-0.8862,  0.5172,  0.9409,  0.0777],
         [-1.2430, -0.2594, -1.6787,  2.0074],
         [-0.2995,  0.6411,  0.6727, -1.9627]]),
 tensor([[1., 1., 1., 1.]]),
 tensor([[ 0.1138,  1.5172,  1.9409,  1.0777],
         [-0.2430,  0.7406, -0.6787,  3.0074],
         [ 0.7005,  1.6411,  1.6727, -0.9627]]))

In [8]:
t4 = torch.randint(10, size = (3, 1))
t4, t4.shape

(tensor([[0],
         [7],
         [8]]),
 torch.Size([3, 1]))

In [9]:
# torch.rand(2, 4) + t2 -> RuntimeError: vì chiều đầu tiên của tensor khác 1

t2 + t4

tensor([[-0.8862,  0.5172,  0.9409,  0.0777],
        [ 5.7570,  6.7406,  5.3213,  9.0074],
        [ 7.7005,  8.6411,  8.6727,  6.0373]])

In [10]:
t5 = torch.full((1, 5), 3) # một chiều thành phần có kích thước là 1
t5, t4,  t5 - t4

(tensor([[3, 3, 3, 3, 3]]),
 tensor([[0],
         [7],
         [8]]),
 tensor([[ 3,  3,  3,  3,  3],
         [-4, -4, -4, -4, -4],
         [-5, -5, -5, -5, -5]]))

In [11]:
# thực hiện với tensor 3D

t6 = torch.randint(22, size = (3,4,5))
t7 = torch.ones(3, 4, 1)

t6, t7, t6 + t7

(tensor([[[ 9, 19,  7,  5, 21],
          [ 7, 17,  5,  8,  0],
          [15,  4,  1,  5, 19],
          [ 2,  3,  7,  6, 19]],
 
         [[10, 10, 20,  3, 20],
          [ 9,  7, 19,  2, 11],
          [12,  8,  7,  8,  0],
          [10, 13,  8, 17, 13]],
 
         [[ 2, 12,  8,  6,  9],
          [15,  4,  8,  9, 11],
          [ 4, 11, 16,  9, 15],
          [ 3, 21, 10,  1, 21]]]),
 tensor([[[1.],
          [1.],
          [1.],
          [1.]],
 
         [[1.],
          [1.],
          [1.],
          [1.]],
 
         [[1.],
          [1.],
          [1.],
          [1.]]]),
 tensor([[[10., 20.,  8.,  6., 22.],
          [ 8., 18.,  6.,  9.,  1.],
          [16.,  5.,  2.,  6., 20.],
          [ 3.,  4.,  8.,  7., 20.]],
 
         [[11., 11., 21.,  4., 21.],
          [10.,  8., 20.,  3., 12.],
          [13.,  9.,  8.,  9.,  1.],
          [11., 14.,  9., 18., 14.]],
 
         [[ 3., 13.,  9.,  7., 10.],
          [16.,  5.,  9., 10., 12.],
          [ 5., 12., 17., 10.,

In [12]:
t8 = torch.randn(3, 1, 5)
t6, t8, t6*t8

(tensor([[[ 9, 19,  7,  5, 21],
          [ 7, 17,  5,  8,  0],
          [15,  4,  1,  5, 19],
          [ 2,  3,  7,  6, 19]],
 
         [[10, 10, 20,  3, 20],
          [ 9,  7, 19,  2, 11],
          [12,  8,  7,  8,  0],
          [10, 13,  8, 17, 13]],
 
         [[ 2, 12,  8,  6,  9],
          [15,  4,  8,  9, 11],
          [ 4, 11, 16,  9, 15],
          [ 3, 21, 10,  1, 21]]]),
 tensor([[[-0.3598, -1.2465,  2.0219, -0.9745,  0.0860]],
 
         [[-0.3071, -0.6167, -1.7156, -0.3513, -0.9697]],
 
         [[-0.0150,  0.1999, -0.5331, -0.1750, -0.8225]]]),
 tensor([[[-3.2381e+00, -2.3683e+01,  1.4153e+01, -4.8723e+00,  1.8066e+00],
          [-2.5185e+00, -2.1190e+01,  1.0109e+01, -7.7956e+00,  0.0000e+00],
          [-5.3969e+00, -4.9860e+00,  2.0219e+00, -4.8723e+00,  1.6345e+00],
          [-7.1958e-01, -3.7395e+00,  1.4153e+01, -5.8467e+00,  1.6345e+00]],
 
         [[-3.0705e+00, -6.1672e+00, -3.4312e+01, -1.0540e+00, -1.9395e+01],
          [-2.7635e+00, -4.3170e+00, -3

In [13]:
t9 = torch.full((3, 1, 1), 3.15) # hai thành phần còn lại có kích thước là 1 

t6 + t9

tensor([[[12.1500, 22.1500, 10.1500,  8.1500, 24.1500],
         [10.1500, 20.1500,  8.1500, 11.1500,  3.1500],
         [18.1500,  7.1500,  4.1500,  8.1500, 22.1500],
         [ 5.1500,  6.1500, 10.1500,  9.1500, 22.1500]],

        [[13.1500, 13.1500, 23.1500,  6.1500, 23.1500],
         [12.1500, 10.1500, 22.1500,  5.1500, 14.1500],
         [15.1500, 11.1500, 10.1500, 11.1500,  3.1500],
         [13.1500, 16.1500, 11.1500, 20.1500, 16.1500]],

        [[ 5.1500, 15.1500, 11.1500,  9.1500, 12.1500],
         [18.1500,  7.1500, 11.1500, 12.1500, 14.1500],
         [ 7.1500, 14.1500, 19.1500, 12.1500, 18.1500],
         [ 6.1500, 24.1500, 13.1500,  4.1500, 24.1500]]])

In [14]:
t7, t7.shape, t8, t8.shape, t7-t8

(tensor([[[1.],
          [1.],
          [1.],
          [1.]],
 
         [[1.],
          [1.],
          [1.],
          [1.]],
 
         [[1.],
          [1.],
          [1.],
          [1.]]]),
 torch.Size([3, 4, 1]),
 tensor([[[-0.3598, -1.2465,  2.0219, -0.9745,  0.0860]],
 
         [[-0.3071, -0.6167, -1.7156, -0.3513, -0.9697]],
 
         [[-0.0150,  0.1999, -0.5331, -0.1750, -0.8225]]]),
 torch.Size([3, 1, 5]),
 tensor([[[ 1.3598,  2.2465, -1.0219,  1.9745,  0.9140],
          [ 1.3598,  2.2465, -1.0219,  1.9745,  0.9140],
          [ 1.3598,  2.2465, -1.0219,  1.9745,  0.9140],
          [ 1.3598,  2.2465, -1.0219,  1.9745,  0.9140]],
 
         [[ 1.3071,  1.6167,  2.7156,  1.3513,  1.9697],
          [ 1.3071,  1.6167,  2.7156,  1.3513,  1.9697],
          [ 1.3071,  1.6167,  2.7156,  1.3513,  1.9697],
          [ 1.3071,  1.6167,  2.7156,  1.3513,  1.9697]],
 
         [[ 1.0150,  0.8001,  1.5331,  1.1750,  1.8225],
          [ 1.0150,  0.8001,  1.5331,  1.1750,  1.82

### 1.3. Tensor khác chiều

Đối với các tensor có số chiều khác nhau, đầu tiên có thể nâng tensor có số chiều thấp lên chiều cao hơn, sau đó áp dụng quy tắc broadcasting của các tensor có cùng chiều khác hình dạng. Việc nâng tensor có số chiều thấp lên chiều cao hơn.

In [15]:
t10 = torch.arange(4).reshape(2, 2)
t10.reshape(1,2,2)

tensor([[[0, 1],
         [2, 3]]])

In [16]:
t11 = torch.arange(12).reshape(3,2,2)
t10.shape, t11.shape, t10+t11

(torch.Size([2, 2]),
 torch.Size([3, 2, 2]),
 tensor([[[ 0,  2],
          [ 4,  6]],
 
         [[ 4,  6],
          [ 8, 10]],
 
         [[ 8, 10],
          [12, 14]]]))

## 2. Phép tính điểm (Pointwise Ops)
Trong PyTorch, phần lớn phép tính điểm đều áp dụng cho từng phần tử trong Tensor và là các phép tính toán học phổ biến, tương tự như các phép tính trên mảng trong NumPy. Các phép tính này chủ yếu bao gồm các phép tính toán cơ bản, phép điều chỉnh giá trị và phép tính khoa học dữ liệu.

### 2.1. Các phép toán cơ bản

In [17]:
a = torch.arange(12).reshape(3, 4)
b = torch.rand(3, 4)
a, b

(tensor([[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]]),
 tensor([[0.0884, 0.8203, 0.8881, 0.9674],
         [0.2355, 0.1630, 0.6093, 0.7927],
         [0.3258, 0.1815, 0.9128, 0.2291]]))

In [18]:
torch.add(a, b), a+b

(tensor([[ 0.0884,  1.8203,  2.8881,  3.9674],
         [ 4.2355,  5.1630,  6.6093,  7.7927],
         [ 8.3258,  9.1815, 10.9128, 11.2291]]),
 tensor([[ 0.0884,  1.8203,  2.8881,  3.9674],
         [ 4.2355,  5.1630,  6.6093,  7.7927],
         [ 8.3258,  9.1815, 10.9128, 11.2291]]))

In [19]:
torch.subtract(a, b), a-b

(tensor([[-0.0884,  0.1797,  1.1119,  2.0326],
         [ 3.7645,  4.8370,  5.3907,  6.2073],
         [ 7.6742,  8.8185,  9.0872, 10.7709]]),
 tensor([[-0.0884,  0.1797,  1.1119,  2.0326],
         [ 3.7645,  4.8370,  5.3907,  6.2073],
         [ 7.6742,  8.8185,  9.0872, 10.7709]]))

In [20]:
torch.multiply(a, b), a*b

(tensor([[0.0000, 0.8203, 1.7762, 2.9021],
         [0.9419, 0.8151, 3.6557, 5.5489],
         [2.6061, 1.6337, 9.1283, 2.5202]]),
 tensor([[0.0000, 0.8203, 1.7762, 2.9021],
         [0.9419, 0.8151, 3.6557, 5.5489],
         [2.6061, 1.6337, 9.1283, 2.5202]]))

In [21]:
torch.divide(a, b), a/b

(tensor([[ 0.0000,  1.2191,  2.2520,  3.1012],
         [16.9869, 30.6704,  9.8476,  8.8306],
         [24.5581, 49.5795, 10.9549, 48.0117]]),
 tensor([[ 0.0000,  1.2191,  2.2520,  3.1012],
         [16.9869, 30.6704,  9.8476,  8.8306],
         [24.5581, 49.5795, 10.9549, 48.0117]]))

### 2.2. Các thao tác điều chỉnh giá trị


In [22]:
t12 = torch.rand(3,4) * 3
t12

tensor([[1.4280, 1.7283, 0.7939, 0.0654],
        [1.4113, 0.9736, 0.0926, 0.7464],
        [0.2469, 0.6317, 0.3020, 2.9542]])

In [23]:
# trị tuyệt đối, làm tròn lên, xuống, tiêu chuẩn, đảo
t12, torch.abs(t12), torch.ceil(t12), torch.floor(t12), torch.round(t12), torch.neg(t12)

(tensor([[1.4280, 1.7283, 0.7939, 0.0654],
         [1.4113, 0.9736, 0.0926, 0.7464],
         [0.2469, 0.6317, 0.3020, 2.9542]]),
 tensor([[1.4280, 1.7283, 0.7939, 0.0654],
         [1.4113, 0.9736, 0.0926, 0.7464],
         [0.2469, 0.6317, 0.3020, 2.9542]]),
 tensor([[2., 2., 1., 1.],
         [2., 1., 1., 1.],
         [1., 1., 1., 3.]]),
 tensor([[1., 1., 0., 0.],
         [1., 0., 0., 0.],
         [0., 0., 0., 2.]]),
 tensor([[1., 2., 1., 0.],
         [1., 1., 0., 1.],
         [0., 1., 0., 3.]]),
 tensor([[-1.4280, -1.7283, -0.7939, -0.0654],
         [-1.4113, -0.9736, -0.0926, -0.7464],
         [-0.2469, -0.6317, -0.3020, -2.9542]]))

In [24]:
t13, t14 = t12.clone(), t12.clone()
t12, t13, t14

(tensor([[1.4280, 1.7283, 0.7939, 0.0654],
         [1.4113, 0.9736, 0.0926, 0.7464],
         [0.2469, 0.6317, 0.3020, 2.9542]]),
 tensor([[1.4280, 1.7283, 0.7939, 0.0654],
         [1.4113, 0.9736, 0.0926, 0.7464],
         [0.2469, 0.6317, 0.3020, 2.9542]]),
 tensor([[1.4280, 1.7283, 0.7939, 0.0654],
         [1.4113, 0.9736, 0.0926, 0.7464],
         [0.2469, 0.6317, 0.3020, 2.9542]]))

In [25]:
# sử dụng '_()' giúp thay đổi trực tiếp giá trị đối tượng gốc

torch.abs_(t13), t13, torch.round_(t14), t14

(tensor([[1.4280, 1.7283, 0.7939, 0.0654],
         [1.4113, 0.9736, 0.0926, 0.7464],
         [0.2469, 0.6317, 0.3020, 2.9542]]),
 tensor([[1.4280, 1.7283, 0.7939, 0.0654],
         [1.4113, 0.9736, 0.0926, 0.7464],
         [0.2469, 0.6317, 0.3020, 2.9542]]),
 tensor([[1., 2., 1., 0.],
         [1., 1., 0., 1.],
         [0., 1., 0., 3.]]),
 tensor([[1., 2., 1., 0.],
         [1., 1., 0., 1.],
         [0., 1., 0., 3.]]))

In [26]:
# một số phương thức của pytorch có thể dùng '_()'

t13.unsqueeze_(0).shape, t13.shape

(torch.Size([1, 3, 4]), torch.Size([1, 3, 4]))

### 2.3. Tính toán khoa học dữ liệu

In [27]:
t13, torch.exp(t13), torch.expm1(t13), torch.pow(t13, 3), torch.sqrt(t13), torch.square(t13)

(tensor([[[1.4280, 1.7283, 0.7939, 0.0654],
          [1.4113, 0.9736, 0.0926, 0.7464],
          [0.2469, 0.6317, 0.3020, 2.9542]]]),
 tensor([[[ 4.1705,  5.6313,  2.2121,  1.0676],
          [ 4.1014,  2.6475,  1.0970,  2.1093],
          [ 1.2801,  1.8809,  1.3525, 19.1856]]]),
 tensor([[[ 3.1705,  4.6313,  1.2121,  0.0676],
          [ 3.1014,  1.6475,  0.0970,  1.1093],
          [ 0.2801,  0.8809,  0.3525, 18.1856]]]),
 tensor([[[2.9121e+00, 5.1629e+00, 5.0047e-01, 2.7996e-04],
          [2.8112e+00, 9.2295e-01, 7.9307e-04, 4.1575e-01],
          [1.5052e-02, 2.5212e-01, 2.7534e-02, 2.5781e+01]]]),
 tensor([[[1.1950, 1.3147, 0.8910, 0.2558],
          [1.1880, 0.9867, 0.3042, 0.8639],
          [0.4969, 0.7948, 0.5495, 1.7188]]]),
 tensor([[[2.0393e+00, 2.9872e+00, 6.3036e-01, 4.2795e-03],
          [1.9919e+00, 9.4795e-01, 8.5679e-03, 5.5704e-01],
          [6.0964e-02, 3.9909e-01, 9.1184e-02, 8.7271e+00]]]))

In [28]:
t13, torch.log(t13), torch.log10(t13), torch.log2(t13), torch.log1p(t13)

(tensor([[[1.4280, 1.7283, 0.7939, 0.0654],
          [1.4113, 0.9736, 0.0926, 0.7464],
          [0.2469, 0.6317, 0.3020, 2.9542]]]),
 tensor([[[ 0.3563,  0.5472, -0.2307, -2.7270],
          [ 0.3445, -0.0267, -2.3799, -0.2926],
          [-1.3987, -0.4593, -1.1974,  1.0832]]]),
 tensor([[[ 0.1547,  0.2376, -0.1002, -1.1843],
          [ 0.1496, -0.0116, -1.0336, -0.1271],
          [-0.6075, -0.1995, -0.5200,  0.4704]]]),
 tensor([[[ 0.5140,  0.7894, -0.3329, -3.9342],
          [ 0.4971, -0.0386, -3.4334, -0.4221],
          [-2.0180, -0.6626, -1.7275,  1.5627]]]),
 tensor([[[0.8871, 1.0037, 0.5844, 0.0634],
          [0.8802, 0.6799, 0.0885, 0.5575],
          [0.2207, 0.4896, 0.2639, 1.3748]]]))

In [29]:
t10, torch.exp(torch.log(t10)), t11, torch.exp2(torch.log2(t11))

(tensor([[0, 1],
         [2, 3]]),
 tensor([[0., 1.],
         [2., 3.]]),
 tensor([[[ 0,  1],
          [ 2,  3]],
 
         [[ 4,  5],
          [ 6,  7]],
 
         [[ 8,  9],
          [10, 11]]]),
 tensor([[[ 0.0000,  1.0000],
          [ 2.0000,  3.0000]],
 
         [[ 4.0000,  5.0000],
          [ 6.0000,  7.0000]],
 
         [[ 8.0000,  9.0000],
          [10.0000, 11.0000]]]))

In [30]:
t15 = torch.arange(0, torch.pi*15, torch.pi/2).reshape(5, 6)
t15, torch.sin(t15), torch.cos(t15), torch.tan(t15), torch.tanh(t15)

(tensor([[ 0.0000,  1.5708,  3.1416,  4.7124,  6.2832,  7.8540],
         [ 9.4248, 10.9956, 12.5664, 14.1372, 15.7080, 17.2788],
         [18.8496, 20.4204, 21.9911, 23.5619, 25.1327, 26.7035],
         [28.2743, 29.8451, 31.4159, 32.9867, 34.5575, 36.1283],
         [37.6991, 39.2699, 40.8407, 42.4115, 43.9823, 45.5531]]),
 tensor([[ 0.0000e+00,  1.0000e+00, -8.7423e-08, -1.0000e+00,  1.7485e-07,
           1.0000e+00],
         [-2.3850e-08, -1.0000e+00,  3.4969e-07,  1.0000e+00, -6.7553e-07,
          -1.0000e+00],
         [ 4.7700e-08,  1.0000e+00,  5.8013e-07, -1.0000e+00,  6.9938e-07,
           1.0000e+00],
         [-7.1549e-08, -1.0000e+00, -5.5628e-07,  1.0000e+00,  1.1841e-06,
          -1.0000e+00],
         [ 9.5399e-08,  1.0000e+00, -1.3749e-06, -1.0000e+00, -1.1603e-06,
           1.0000e+00]]),
 tensor([[ 1.0000e+00, -4.3711e-08, -1.0000e+00,  1.1925e-08,  1.0000e+00,
           1.3907e-07],
         [-1.0000e+00, -2.9007e-07,  1.0000e+00, -3.5775e-08, -1.0000e+00,
  

In [31]:
# sắp xếp
t13, t13.sort(), torch.sort(t13)

(tensor([[[1.4280, 1.7283, 0.7939, 0.0654],
          [1.4113, 0.9736, 0.0926, 0.7464],
          [0.2469, 0.6317, 0.3020, 2.9542]]]),
 torch.return_types.sort(
 values=tensor([[[0.0654, 0.7939, 1.4280, 1.7283],
          [0.0926, 0.7464, 0.9736, 1.4113],
          [0.2469, 0.3020, 0.6317, 2.9542]]]),
 indices=tensor([[[3, 2, 0, 1],
          [2, 3, 1, 0],
          [0, 2, 1, 3]]])),
 torch.return_types.sort(
 values=tensor([[[0.0654, 0.7939, 1.4280, 1.7283],
          [0.0926, 0.7464, 0.9736, 1.4113],
          [0.2469, 0.3020, 0.6317, 2.9542]]]),
 indices=tensor([[[3, 2, 0, 1],
          [2, 3, 1, 0],
          [0, 2, 1, 3]]])))

In [32]:
t13, t13.sort(descending=True)

(tensor([[[1.4280, 1.7283, 0.7939, 0.0654],
          [1.4113, 0.9736, 0.0926, 0.7464],
          [0.2469, 0.6317, 0.3020, 2.9542]]]),
 torch.return_types.sort(
 values=tensor([[[1.7283, 1.4280, 0.7939, 0.0654],
          [1.4113, 0.9736, 0.7464, 0.0926],
          [2.9542, 0.6317, 0.3020, 0.2469]]]),
 indices=tensor([[[1, 0, 2, 3],
          [0, 1, 3, 2],
          [3, 1, 2, 0]]])))

## 3. Phép tính rút gọn (Reduction Ops)
Loại phép tính này bao gồm nhiều hàm thống kê trong lĩnh vực khoa học dữ liệu, như hàm trung bình, hàm cực đại, hàm phương sai, hàm trung vị,...

In [35]:
t15, torch.mean(t15), torch.var(t15), torch.std(t15), torch.var_mean(t15), torch.std_mean(t15)

(tensor([[ 0.0000,  1.5708,  3.1416,  4.7124,  6.2832,  7.8540],
         [ 9.4248, 10.9956, 12.5664, 14.1372, 15.7080, 17.2788],
         [18.8496, 20.4204, 21.9911, 23.5619, 25.1327, 26.7035],
         [28.2743, 29.8451, 31.4159, 32.9867, 34.5575, 36.1283],
         [37.6991, 39.2699, 40.8407, 42.4115, 43.9823, 45.5531]]),
 tensor(22.7765),
 tensor(191.2236),
 tensor(13.8284),
 (tensor(191.2236), tensor(22.7765)),
 (tensor(13.8284), tensor(22.7765)))

In [38]:

torch.max(t15), torch.argmax(t15), torch.min(t15), torch.argmin(t15), torch.median(t15)

(tensor(45.5531), tensor(29), tensor(0.), tensor(0), tensor(21.9911))

In [52]:
t13, torch.sum(t13), torch.prod(t13), torch.logsumexp(t13, -1), torch.topk(t13, 1, 2) # ()?

(tensor([[[1.4280, 1.7283, 0.7939, 0.0654],
          [1.4113, 0.9736, 0.0926, 0.7464],
          [0.2469, 0.6317, 0.3020, 2.9542]]]),
 tensor(11.3744),
 tensor(0.0017),
 tensor([[2.5712, 2.2981, 3.1654]]),
 torch.return_types.topk(
 values=tensor([[[1.7283],
          [1.4113],
          [2.9542]]]),
 indices=tensor([[[1],
          [0],
          [3]]])))

hàm `dist()` được sử dụng để tính khoảng cách giữa hai tensor. Hàm này thường được sử dụng trong các tác vụ như tính khoảng cách Euclidean giữa các điểm dữ liệu, tính khoảng cách cosine, hoặc tính khoảng cách Mahalanobis.

In [55]:
torch.dist(t12, t14, p=2), torch.sqrt(torch.square(t14-t12).sum()) # khoảng cách Euclidean

(tensor(0.9146), tensor(0.9146))

In [57]:

# khoảng cách Manhattan 

torch.dist(t12, t14, p=1), torch.sum((t12-t14).abs())

(tensor(2.7181), tensor(2.7181))

In [60]:
# chỉ định chiều tính toán

t12, torch.sum(t12, 0), torch.sum(t12, 1) # theo hàng, theo cột

(tensor([[1.4280, 1.7283, 0.7939, 0.0654],
         [1.4113, 0.9736, 0.0926, 0.7464],
         [0.2469, 0.6317, 0.3020, 2.9542]]),
 tensor([3.0863, 3.3337, 1.1885, 3.7659]),
 tensor([4.0157, 3.2239, 4.1348]))

In [67]:

t13, torch.mean(t13), torch.mean(t13, dim=0), t13.mean(0)

(tensor([[[1.4280, 1.7283, 0.7939, 0.0654],
          [1.4113, 0.9736, 0.0926, 0.7464],
          [0.2469, 0.6317, 0.3020, 2.9542]]]),
 tensor(0.9479),
 tensor([[1.4280, 1.7283, 0.7939, 0.0654],
         [1.4113, 0.9736, 0.0926, 0.7464],
         [0.2469, 0.6317, 0.3020, 2.9542]]),
 tensor([[1.4280, 1.7283, 0.7939, 0.0654],
         [1.4113, 0.9736, 0.0926, 0.7464],
         [0.2469, 0.6317, 0.3020, 2.9542]]))

In [81]:
t6, torch.sort(t6), torch.sort(t6, dim=1), t6.sort(0), t6.sort(dim=2, descending=True)

(tensor([[[ 9, 19,  7,  5, 21],
          [ 7, 17,  5,  8,  0],
          [15,  4,  1,  5, 19],
          [ 2,  3,  7,  6, 19]],
 
         [[10, 10, 20,  3, 20],
          [ 9,  7, 19,  2, 11],
          [12,  8,  7,  8,  0],
          [10, 13,  8, 17, 13]],
 
         [[ 2, 12,  8,  6,  9],
          [15,  4,  8,  9, 11],
          [ 4, 11, 16,  9, 15],
          [ 3, 21, 10,  1, 21]]]),
 torch.return_types.sort(
 values=tensor([[[ 5,  7,  9, 19, 21],
          [ 0,  5,  7,  8, 17],
          [ 1,  4,  5, 15, 19],
          [ 2,  3,  6,  7, 19]],
 
         [[ 3, 10, 10, 20, 20],
          [ 2,  7,  9, 11, 19],
          [ 0,  7,  8,  8, 12],
          [ 8, 10, 13, 13, 17]],
 
         [[ 2,  6,  8,  9, 12],
          [ 4,  8,  9, 11, 15],
          [ 4,  9, 11, 15, 16],
          [ 1,  3, 10, 21, 21]]]),
 indices=tensor([[[3, 2, 0, 1, 4],
          [4, 2, 0, 3, 1],
          [2, 1, 3, 0, 4],
          [0, 1, 3, 2, 4]],
 
         [[3, 0, 1, 2, 4],
          [3, 1, 0, 4, 2],
        

## 4. Phép so sánh (Comparison Ops)

In [86]:
# so sánh các phần tử 2 tensor cùng kích thước

c = torch.rand(3, 4)
d = torch.randn(3, 4)

c, d, torch.gt(c, d), c>d

(tensor([[0.0511, 0.6093, 0.4979, 0.5834],
         [0.1623, 0.4379, 0.0035, 0.6991],
         [0.0733, 0.0212, 0.7996, 0.9534]]),
 tensor([[ 0.9190,  0.3510,  1.2850,  0.1170],
         [-0.6527, -0.6337, -0.1897, -0.5935],
         [-0.9939, -2.0683, -0.0927,  0.6814]]),
 tensor([[False,  True, False,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[False,  True, False,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [87]:
torch.eq(c, d), c==d

(tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[False, False, False, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [88]:
torch.lt(c, d), c<d

(tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [89]:
torch.ge(c, d), c>=d

(tensor([[False,  True, False,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]),
 tensor([[False,  True, False,  True],
         [ True,  True,  True,  True],
         [ True,  True,  True,  True]]))

In [90]:
torch.le(c, d), c<=d

(tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]),
 tensor([[ True, False,  True, False],
         [False, False, False, False],
         [False, False, False, False]]))

In [91]:
torch.ne(c, d), c!=d

(tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]),
 tensor([[True, True, True, True],
         [True, True, True, True],
         [True, True, True, True]]))